Avoid errors when options.cfg has no data
In that case res==False which was not accounted for, resulting in
AttributeError: 'bool' object has no attribute 'items'.

Closes #193.