Fix command line option error message
TypeError: unsupported operand type(s) for +: 'GetoptError' and 'str'
caused by commit 65b86f2d1d6f53fef133af897c673568205ce7a3